# Generated by Django 3.2.3 on 2021-06-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_h2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='h2',
        ),
    ]
