# Generated by Django 3.2.3 on 2021-05-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendars',
            options={'verbose_name': 'Calendar'},
        ),
        migrations.AlterField(
            model_name='calendars',
            name='date',
            field=models.DateField(),
        ),
    ]
