# Generated by Django 3.2.3 on 2021-05-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20210514_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendars',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
