# Generated by Django 3.2.3 on 2021-06-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_alter_calendars_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendars',
            name='subname',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='calendars',
            name='description',
            field=models.CharField(default=True, max_length=1000),
        ),
    ]
