# Generated by Django 3.2.3 on 2021-06-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_calenimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calenimg',
            name='file',
            field=models.ImageField(null=True, upload_to='Ca_photos'),
        ),
    ]
