# Generated by Django 3.2.3 on 2021-06-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0007_alter_calenimg_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalenImg',
        ),
    ]
