# Generated by Django 3.2.3 on 2021-06-16 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0008_delete_calenimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, null=True)),
                ('file', models.ImageField(null=True, upload_to='ca_photos')),
                ('calen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caimg', to='calendars.calendars')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
