# Generated by Django 3.2.3 on 2021-06-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0009_calenimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendars',
            name='date',
            field=models.CharField(default=True, max_length=80),
        ),
    ]
