# Generated by Django 3.2.3 on 2021-06-04 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20210514_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='ChannelImg',
        ),
        migrations.AlterModelOptions(
            name='channelimg',
            options={'verbose_name': 'Channel Img'},
        ),
        migrations.AddField(
            model_name='channel',
            name='channelimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cannelimg', to='channel.channelimg'),
        ),
    ]
