# Generated by Django 3.2.3 on 2021-06-04 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20210604_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channelimg',
        ),
        migrations.AddField(
            model_name='channelimg',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='channel.channel'),
        ),
        migrations.AddField(
            model_name='channelimg',
            name='file',
            field=models.ImageField(null=True, upload_to='Ch_photos'),
        ),
    ]
