# Generated by Django 3.2.3 on 2021-06-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_auto_20210604_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelimg',
            options={},
        ),
        migrations.RemoveField(
            model_name='channelimg',
            name='channel',
        ),
        migrations.AddField(
            model_name='channel',
            name='channelimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='channel.channelimg'),
        ),
        migrations.AddField(
            model_name='channelimg',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
