# Generated by Django 3.2.3 on 2021-06-04 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_auto_20210604_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channelimg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelimg', to='channel.channelimg'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channeltype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channeltype', to='channel.channeltype'),
        ),
    ]
