# Generated by Django 3.2.3 on 2021-06-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_auto_20210604_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelimg',
            old_name='file',
            new_name='chimg',
        ),
    ]
