# Generated by Django 3.2.3 on 2021-06-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_rename_chimg_channelimg_th'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelimg',
            old_name='th',
            new_name='file',
        ),
    ]
