# Generated by Django 3.2.3 on 2021-06-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_rename_th_channelimg_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channelimg',
        ),
        migrations.AddField(
            model_name='channelimg',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='channel.channel'),
        ),
        migrations.AlterField(
            model_name='channelimg',
            name='file',
            field=models.ImageField(null=True, upload_to='ch_photos'),
        ),
    ]
