# Generated by Django 3.2.3 on 2021-06-09 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0011_auto_20210609_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channeltype',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channeltype', to='channel.channeltype'),
        ),
    ]
